### ISSUE TITLE
Correção ortográfica

### ISSUE THREAD

**Issue by felpsalvs** [jacksonadh/Learn-NextJS#1]
Ei Jackson, tudo bem cara? quanto tempo. Eu resolvi dar uma olhadinha no teu repositório e está muito bacana, gostei demais. Resolvi só sugerir uma correção ortográfica simples no About do repositório. Acredito que passou sem perceber, mas ao invés de "tuturial", não seria "tutorial"? Caso já tenha visto, desconsidere essa issue!

**Comment by jacksonadh** [comment]
Fala @felpsalvs tudo tranquilo, muito obrigado pela observação. Vou corrigir aqui!
